#!/bin/sh

fastboot flash partition gpt_both0.bin
fastboot flash hyp hyp.mbn
fastboot flash rpm rpm.mbn
fastboot flash sbl1 sbl1.mbn
fastboot flash tz tz-psci.mbn
fastboot flash aboot emmc_appsboot.mbn
fastboot flash cdt cdt_1.1_MT52L256M32D1PF.bin

fastboot erase boot
fastboot erase rootfs
fastboot erase devinfo
fastboot erase sec
fastboot erase recovery
fastboot erase misc
fastboot erase cache
